### PR TITLE
Update composer.yml

### PR DESCRIPTION
**Pull request by markitosgv**
Need to export SYMFONY_ENV variable before execute composer install to avoid clear cache on dev env

### CODE REVIEW

**Comment by geevcookie** [comment]
Could you please provide more information for why this is required? The way it was written exports the environment variable for the duration of the command. Did you run into issues with this?

**Comment by markitosgv** [comment]
Yes, when execute tries to install require dev dependencies

**Comment by geevcookie** [comment]
Can you perhaps provide the error?

**Comment by geevcookie** [comment]
No feedback and unable to find any issues. Feel free to reopen with more information if you experience any further issues.

**Pull request closed without merging**
